"""Kafka / Parquet event schema — contract from Step 7 (schema_contract.json)."""

from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

# 59 feature columns + Label (matches stream_holdout Parquet)
EVENT_SCHEMA = StructType(
    [
        StructField("Destination Port", IntegerType(), True),
        StructField("Flow Duration", IntegerType(), True),
        StructField("Total Fwd Packets", IntegerType(), True),
        StructField("Total Backward Packets", IntegerType(), True),
        StructField("Total Length of Fwd Packets", IntegerType(), True),
        StructField("Total Length of Bwd Packets", IntegerType(), True),
        StructField("Fwd Packet Length Max", IntegerType(), True),
        StructField("Fwd Packet Length Min", IntegerType(), True),
        StructField("Fwd Packet Length Mean", DoubleType(), True),
        StructField("Fwd Packet Length Std", DoubleType(), True),
        StructField("Bwd Packet Length Max", IntegerType(), True),
        StructField("Bwd Packet Length Min", IntegerType(), True),
        StructField("Bwd Packet Length Mean", DoubleType(), True),
        StructField("Bwd Packet Length Std", DoubleType(), True),
        StructField("Flow Bytes/s", DoubleType(), True),
        StructField("Flow Packets/s", DoubleType(), True),
        StructField("Flow IAT Mean", DoubleType(), True),
        StructField("Flow IAT Std", DoubleType(), True),
        StructField("Flow IAT Max", IntegerType(), True),
        StructField("Flow IAT Min", IntegerType(), True),
        StructField("Fwd IAT Total", IntegerType(), True),
        StructField("Fwd IAT Mean", DoubleType(), True),
        StructField("Fwd IAT Std", DoubleType(), True),
        StructField("Fwd IAT Max", IntegerType(), True),
        StructField("Fwd IAT Min", IntegerType(), True),
        StructField("Bwd IAT Total", IntegerType(), True),
        StructField("Bwd IAT Mean", DoubleType(), True),
        StructField("Bwd IAT Std", DoubleType(), True),
        StructField("Bwd IAT Max", IntegerType(), True),
        StructField("Bwd IAT Min", IntegerType(), True),
        StructField("Fwd Header Length34", LongType(), True),
        StructField("Bwd Header Length", IntegerType(), True),
        StructField("Fwd Packets/s", DoubleType(), True),
        StructField("Bwd Packets/s", DoubleType(), True),
        StructField("Min Packet Length", IntegerType(), True),
        StructField("Max Packet Length", IntegerType(), True),
        StructField("Packet Length Mean", DoubleType(), True),
        StructField("Packet Length Std", DoubleType(), True),
        StructField("Packet Length Variance", DoubleType(), True),
        StructField("FIN Flag Count", IntegerType(), True),
        StructField("SYN Flag Count", IntegerType(), True),
        StructField("RST Flag Count", IntegerType(), True),
        StructField("PSH Flag Count", IntegerType(), True),
        StructField("ACK Flag Count", IntegerType(), True),
        StructField("Down/Up Ratio", IntegerType(), True),
        StructField("Average Packet Size", DoubleType(), True),
        StructField("Avg Fwd Segment Size", DoubleType(), True),
        StructField("Avg Bwd Segment Size", DoubleType(), True),
        StructField("Fwd Header Length55", LongType(), True),
        StructField("act_data_pkt_fwd", IntegerType(), True),
        StructField("min_seg_size_forward", IntegerType(), True),
        StructField("Active Mean", DoubleType(), True),
        StructField("Active Std", DoubleType(), True),
        StructField("Active Max", IntegerType(), True),
        StructField("Active Min", IntegerType(), True),
        StructField("Idle Mean", DoubleType(), True),
        StructField("Idle Std", DoubleType(), True),
        StructField("Idle Max", IntegerType(), True),
        StructField("Idle Min", IntegerType(), True),
        StructField("Label", StringType(), True),
    ]
)

KAFKA_ENVELOPE_SCHEMA = StructType(
    [
        StructField("kafka_key", StringType(), True),
        StructField("kafka_timestamp", TimestampType(), True),
        StructField("sensor_id", StringType(), True),
        StructField("event_time", TimestampType(), True),
        StructField("source_ip", StringType(), True),
        *EVENT_SCHEMA.fields,
    ]
)
